spring:
  application:
    name: redis-time
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  error:
    include-message: always

application:
  redis-config:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}