spring:
  application:
    name: redis-time
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  error:
    include-message: always

application:
  stream-config:
    stream-key: "TEST_STREAM"
    group: "TEST_GROUP"
